services:
  taptap-mqtt:
    image: ghcr.io/godel00/taptap-mqtt-docker:latest
    container_name: taptap-mqtt
    cap_add:
      - SYS_RESOURCE
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped